### ISSUE TITLE
Validating tokens that don't have claims like "sub"

### ISSUE THREAD

**Issue by ItalyPaleAle** [auth0/idtoken-verifier#123]
### Describe the problem you'd like to have solved

I am working with a service that returns JWT without a "sub" claim, and trying to validate it with this library throw an exception.

According to the RFC ([section 4.1](https://tools.ietf.org/html/rfc7519#section-4.1)) all claims are optional, but this library expects (and requires) certain claims to be present: iss, sub, aud, nbf, iat

### Describe the ideal solution

There should be a way to tell this library which claims to validate. 

## Alternatives and current work-arounds

There's no workaround besides forking this library (or using another one).

**Comment by stevehobbsdev** [comment]
Thanks for raising this @ItalyPaleAle - let me have a discussion internally around this and come back to you.

**Comment by stevehobbsdev** [comment]
This library implements ID token validation according to the [OpenID Core spec](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) where the `sub` claim (and others) are required, rather than being a generic JWT validation library.

As such, we'll be unable to accommodate this feature request. I'll close for now but happy to discuss further if you have questions.
